NO_USERNAME = {'error_code': 'USER-1', 'message': 'username is none'}
NO_PASSWORD = {'error_code': 'USER-2', 'message': 'password is none'}
NO_EMAIL = {'error_code': 'USER-3', 'message': 'email is none'}
NO_FIRST_NAME = {'error_code': 'USER-4', 'message': 'first_name is none'}
NO_LAST_NAME = {'error_code': 'USER-5', 'message': 'last_name is none'}
EMAIL_EXISTS = {'error_code': 'USER-6', 'message': 'This e-mail already exists'}
USERNAME_EXISTS = {'error_code': 'USER-7', 'message': 'This username already exists'}
OFFSET_IS_NOT_INT = {'error_code': 'USER-8', 'message': 'offset is not int'}
LIMIT_IS_NOT_INT = {'error_code': 'USER-9', 'message': 'limit is not int'}
NO_NAME = {'error_code': 'USER-10', 'message': 'name is none'}
NO_PFP = {'error_code': 'USER-11', 'message': 'pfp is none'}
